[package]
name = "tigerbeetle"
version = "0.13.3"
edition = "2021"
license = "MIT"

[dependencies]
tigerbeetle-sys = { version = "0.13.3", path = "sys", features = ["generated-safe"] }
futures-channel = "0.3.28"
bytemuck = "1.13.1"
tokio = { version = "1.28.1", features = ["sync"] }

[dev-dependencies]
pollster = { version = "0.3.0", features = ["macro"] }

[workspace]
members = ["sys"]
