[package]
name = "tigerbeetle"
version = "0.1.0"
edition = "2021"
license = "MIT"

[dependencies]
tigerbeetle-sys = { version = "0.1.0", path = "sys", features = ["generated-safe"] }

[workspace]
members = ["sys"]
