[package]
name = "tigerbeetle-core"
version = "0.2.0+0.13.36"
edition = "2021"

[dependencies]
tigerbeetle-sys = { version = "0.13.36", path = "../sys", features = ["generated-safe"] }
bytemuck = "1.13.1"
sptr = "0.3.2"
