name: Check new version

on:
  schedule:
    - cron: "42 7 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - run: .github/upgrade-ver.sh
        id: new

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          commit-message: Upgrade to ${{ steps.new.outputs.version }} TigerBeetle
          branch: upgrade-to-${{ steps.new.outputs.version }}
          delete-branch: true
          title: Upgrade to ${{ steps.new.outputs.version }} TigerBeetle
          body: Upgrade to new ${{ steps.new.outputs.version }} version of TigerBeetle.
          labels: |
            enhancement
            k::dependencies
            k::version
            zig
